config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    belongs_to :user
    validates_associated :user 
end

app/models/user.rb
class User < ApplicationRecord
    has_many :blogs
    validates_inclusion_of :name, :in => %w( m f )
    validates_exclusion_of :name, :in => %w( admin administrator )
    validates_uniqueness_of :name, :case_sensitive => true
    validates_uniqueness_of :email, :case_sensitive => false
    validates_confirmation_of :email
    validates :name, presence: true,
                     length: { minimum: 1}
    validates :email, presence: true,
                      length: { minimum: 1}
                      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
        redirect_to @user
    else
        render 'new'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
        redirect_to @user 
    else
        render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @user = User.all
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private
    def user_params
        params.require(:user).permit(:name, :email, :bio)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BetterErrorMsg</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with model: @user, local: true do |form| %>
 
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </p>
 
  <p>
    <%= form.label :bio %><br>
    <%= form.text_area :bio %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
<% end %>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= render 'form' %>
 
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<%= link_to 'New user', new_user_path %>
 
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Bio</th>
    <th></th>
  </tr>
 
  <% @user.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.bio %></td>
      <td><%= link_to 'Show', user_path(user) %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user_path(user),
              method: :delete,
              data: { confirm: 'Are you sure you want to delete this user?'} %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Back', welcome_index_path %>

app/views/users/new.html.erb
<h1>New user</h1>
 
<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name%>
</p>
 
<p>
  <strong>Email:</strong>
  <%= @user.email%>
</p>

<p>
  <strong>Bio:</strong>
  <%= @user.bio%>
</p>

<%= link_to 'Edit', edit_user_path %>
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<!-- <h1>Welcome#index</h1> -->
<!-- <p>Find me in app/views/welcome/index.html.erb</p> -->
<h1>Hello, Rails!</h1>
<%= link_to 'List Users', controller: 'users' %>